scan:
  name: Skanuj kamerę
  description: Wykonuje rozpoznanie tablic dla wskazanej kamery lub wszystkich kamer.
  target:
    entity:
      integration: enhanced_platerecognizer
      domain: image_processing

add_plate:
  name: Dodaj tablicę
  description: Dodaje nową tablicę do listy znanych tablic.
  fields:
    plate:
      name: Tablica rejestracyjna
      description: Numer tablicy do dodania
      required: true
      example: LUB3536P
    owner:
      name: Właściciel
      description: Nazwa właściciela (opcjonalnie)
      required: false

remove_plate:
  name: Usuń tablicę
  description: Usuwa tablicę z listy znanych tablic.
  fields:
    plate:
      name: Tablica rejestracyjna
      description: Numer tablicy do usunięcia
      required: true

clean_images:
  name: Czyść zdjęcia
  description: Usuwa najstarsze zdjęcia, pozostawiając tylko określoną liczbę najnowszych.
  fields:
    folder:
      name: Folder
      description: Ścieżka folderu ze zdjęciami (opcjonalnie)
      required: false
    max_images:
      name: Maksymalna liczba zdjęć
      description: Ile najnowszych zdjęć ma zostać (opcjonalnie, domyślnie z ustawień integracji)
      required: false
